INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Howard the Duck', 110, 'Sci-Fi', 4.6, 'PG');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Lavalantula', 83, 'Horror', 4.7, 'TV-14');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Starship Troopers', 129, 'Sci-Fi', 7.2, 'PG-13');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Waltz With Bashir', 90, 'Documentary', 8.0, 'R');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Spaceballs', 96, 'Comedy', 7.1, 'PG');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Monsters Inc.', 92, 'Animation', 8.1, 'G');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Kung fu Hustle', 99, 'Action', 7.6, 'R');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('My Cousin Vinnie', 120, 'Comedy', 7.6, 'R');


SELECT * FROM MOVIES WHERE GENRE = 'Sci-Fi';
SELECT * FROM MOVIES WHERE IMDB_SCORE>=6.5;
SELECT * FROM MOVIES WHERE RUNTIME<100 AND (RATING='PG' OR RATING='G');
SELECT AVG(RUNTIME), GENRE FROM  (SELECT * FROM MOVIES WHERE IMDB_SCORE<7.5) AS MINIMOVIES GROUP BY GENRE;
UPDATE MOVIES SET RATING='R' WHERE TITLE='Starship Troopers';
SELECT ID, RATING FROM MOVIES WHERE GENRE='Horror' OR GENRE='Documentary';
SELECT  AVG(IMDB_SCORE), MAX(IMDB_SCORE), MIN(IMDB_SCORE), RATING FROM MOVIES GROUP BY RATING;
SELECT  AVG(IMDB_SCORE), MAX(IMDB_SCORE), MIN(IMDB_SCORE), RATING FROM MOVIES GROUP BY RATING HAVING COUNT(*)>1;
DELETE FROM MOVIES WHERE RATING='R';